### ISSUE TITLE
After upgrading to XCode 6.4, the RoboVM Run/Debug configurations no longer work

### ISSUE THREAD

**Issue by tylerpitchford** [robovm/robovm-studio#8] opened 2015-07-02 16:03 UTC
After updating to XCode 6.4 yesterday, the Run/Debug configurations now show blanks for:

Attached device:

  Signing Identity; 
  Provisioning Profile;

Simulator:

  Device Type

I attempted to set them from the build.gradle and reimport, but the settings were ignored. Launching from the command line with the build.gradle fails under launchIOSDevice.

If you attempt to launch the simulators from the command line, a ArrayIndexOutOfBoundsException is thrown when loading the devices available:

gradle launchIPhoneSimulator --stacktrace
:launchIPhoneSimulator FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launchIPhoneSimulator'.
> 1

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':launchIPhoneSimulator'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:306)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at org.robovm.compiler.target.ios.DeviceType.listDeviceTypes(DeviceType.java:112)
	at org.robovm.compiler.target.ios.DeviceType.getBestDeviceType(DeviceType.java:221)
	at org.robovm.gradle.tasks.AbstractIOSSimulatorTask.getDeviceType(AbstractIOSSimulatorTask.java:96)
	at org.robovm.gradle.tasks.IPhoneSimulatorTask.invoke(IPhoneSimulatorTask.java:28)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 44 more

The same exception is thrown in the IDE.

**Comment by badlogic** [comment] 2015-07-02 16:05
Thanks for reporting. We are scheduling a new studio release for next week.
I've confirmed the RoboVM IDEA plugin to work with Xcode 6.4. Please give
the snapshot a try, in either IDEA or RoboVM Studio. You can find it at
http://download.robovm.com

**Comment by badlogic** [comment] 2015-07-02 16:08
Oh, one more thing. Try opening Xcode and go to Xcode -> Preferences ->
Accounts. Make sure you agree to any new TOS and potentially synch you
signing identities and provisioning profiles.

**Comment by tylerpitchford** [comment] 2015-07-02 16:11
Everything is synched, the first thing I tried actually. And did you mean http://download.robovm.org? The other link is dead. 

Downloading now; I'll update when I get it installed.

Best,
Tyler

**Comment by tylerpitchford** [comment] 2015-07-02 16:37
I tried installing under my RoboVM 1.4 EAP installation, but I get a message:

"Plugin 'RoboVM IntelliJ IDEA Plugin' is incompatible with this installation."

I tried removing the old RoboVM plugin before installing, but got the same result.

**Comment by badlogic** [comment] 2015-07-02 16:40
Sorry for the inconvenience, the Studio EAP has it's API version set
incorrectly. If you are in a hurry, i suggest getting IDEA community
edition plus the RoboVM plugin snapshot. Again, sorry, you are living on
the edge with the EAP :)

**Comment by tylerpitchford** [comment] 2015-07-02 16:47
No worries at all, thanks for the quick updates!

Great work by the way.

**Comment by badlogic** [comment] 2015-07-13 11:20
Could you give the latest and greatest a try and report back?

**Comment by GitCatavolt** [comment] 2015-07-20 15:28
I just reopened the project and it's showing up blank. I'll try to make a new one and see if that fixes anything.

**Comment by badlogic** [comment] 2015-08-06 12:37
This should be fixed with the 1.6 release. Please let us know if it doesn't fix it for you. I was unable to reproduce it locally and could only go by your log.

**Closed by badlogic** 2015-08-06 12:37 UTC
Labels: bug
